### ISSUE TITLE
Hola, cómo es el tema del ubigeo para extranjeros que fueron nacionalizados por sus padres.

### ISSUE THREAD

**Issue by pierreramiro** [jmcastagnetto/ubigeo-peru-aumentado#1]
Al ingresar el ubigeo de mi dni en plataformas que me lo solicitan, me dice que 

"Ubigeo no coincide con datos de la reniec"

Como podría saber mi ubigeo, o un aproximado del mismo?

**Comment by jmcastagnetto** [comment]
Lo siento, pero eso es algo que tienes que preguntar a RENIEC, pues no tengo idea de como lo manejan. 
Revisa si encuentras tu UBIGEO en lo que he publicado aquí, de otro modo, si no está es porque puede ser un código interno de RENIEC que no es público.

**Comment by pierreramiro** [comment]
Solucioné mi asunto, al paracer es un tema de las plataformas. Verificamos que en RENIEC si sale dicho ubigeo, pero en las plataformas hay un error cuando el ubigeo es de un pais extranjero. Espero este comentario pueda ayudar a otros.

 Gracias @jmcastagnetto  igualmente por su respuesta.
